spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: user
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  api-docs:
    path: /api-docs
    enabled: true # for dev
  swagger-ui:
    enabled: true # for dev
    path: /swagger-ui.html
    try-it-out-enabled: true
  packages-to-scan: io.chagchagchag.ddd.fastcampus_v1.membership.adapter.in.web
  cache:
    disabled: true
  version: v1
